[package]
name = "firewall"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13.1", features = ["async_tokio"] }
aya-log = "0.2"
firewall-common = { path = "../firewall-common", features = ["user"] }
tokio = { version = "1.49.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "time"] }
env_logger = "0.10"
log = "0.4"
anyhow = "1"
bytes = "1"
clap = {version = "4", features = ["derive"]}
futures = "0.3"
libc = "0.2"
